### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by jatty**

### CODE REVIEW

**Comment by mutantcornholio** [comment]
Any chance of merging this? @odarriba

**Comment by odarriba** [comment]
Hello,

I'm sorry, but seeing the changes I'm not really getting why python needs to be updated and the PR description/title is not clear. What´s the issue?

Also, there is an updated branch called `smb` which is updated for latest MacOS versions.
Have you tried it?

**Comment by mutantcornholio** [comment]
There's no more `python` package in `alpine:latest`. I've tried to rebuild the image yesterday, bumped into the issue.

**Comment by odarriba** [comment]
Merging then! However, I encourage you to test the samba version, as will be default soon.

**Comment by mutantcornholio** [comment]
Actually, I turned to your repo when I had enough of samba-related problems and wanted to try netatalk ;)
And it worked like a charm for almost a year

**Pull request merged**
